### ISSUE TITLE
Hot deploy for native pluggable widget updates web deployment folder rather than native

### ISSUE THREAD

**Issue by mgroeneweg** [mendix/pluggable-widgets-generator#12]
I have hot deploy issues with version 0.1.4. For native pluggable widgets, the hot deploy updates the deployment/web/... folder in the test project, where it should update deployment/native/...

Can be seen by creating a native pluggable boiler plate widget, configure the test project location to your preference. In the test project, clean the deployment folder. Then build the widget.

**Comment by diego-antonelli** [comment]
Fixed in version 0.1.7 of Pluggable Widgets Tools [https://github.com/mendix/pluggable-widgets-tools]
