### ISSUE TITLE
Hot deploy for hybrid/online pluggable widget fails.

### ISSUE THREAD

**Issue by mgroeneweg** [mendix/pluggable-widgets-generator#13]
Hi,

Whenever the online/hybrid pluggable widget sources are changed, the widget is rebuilt. React complains that hot deployment is attempted in a production environment. Indeed, hot deploy does not work. A full stop/start of the runtime is required to test widget changes.

Can be seen by following the pluggable widget how to document, step 1 is sufficient.

**Comment by diego-antonelli** [comment]
Fixed in version 8.0.0

**Comment by mgroeneweg** [comment]
@diego-antonelli So how would I update an existing widget project to take advantage of the fix? I generated a new widget just to check and it seems the package.json is changed way more than just a couple of dependency versions.

**Comment by diego-antonelli** [comment]
@mgroeneweg you should open a question in the forum, this is not an issue anymore. Or send us your package.json to check.

**Comment by mgroeneweg** [comment]
@diego-antonelli I disagree. The bug has been fixed but now I need to implement the fix and I don't know what to fix. However, I think I will just recreate the widget project and move the sources. So we can leave it at that.

**Comment by diego-antonelli** [comment]
@mgroeneweg As I said, just send me your package.json or the content of the same and I can figure it out what is happening. Basically you should keep your @types dependencies and just add "pluggable-widgets-tools": "^8.0.2" as main dependency.

** You were using the beta version before (lower than 1), this is the oficial release (8.0.0) for Mendix 8

**Comment by mgroeneweg** [comment]
@diego-antonelli I had not realized I was on a beta at first. That changes things. It also explains the many differences. I will just start fresh then and ask my colleague to do the same. Thanks for all the help!

**Comment by diego-antonelli** [comment]
@mgroeneweg no problem, if you have any problem again, feel free to contact us or open a new issue.
