### ISSUE TITLE
Following howto step 3.2, yeoman crashes

### ISSUE THREAD

**Issue by JbmmMx** [mendix/pluggable-widgets-generator#24]
Hi, 
following the mendix howto step by step, I keep running into errors when running the yo command.
Howto: https://docs.mendix.com/howto/extensibility/create-a-pluggable-widget-one
Step: 3.2
Command: yo @mendix/widget TextBox
first ERR! lines: 
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
...

Versions: StudioPro(8.0.0), Nodejs(v8.16.0), npm(6.10.0)

Did I miss any Prerequisites? Does the howto instruction miss something?
Full logging looks something might be wrong with nodejs command?

**Comment by diego-antonelli** [comment]
Hi @JbmmMx it seems to be something wrong with your local Python. Can you please install it?

https://www.python.org/downloads/

Or maybe update your node to 10.15 or 12, we don't recommend version 8.16.0

**Comment by JbmmMx** [comment]
Status: 
installed Python 3.7, reboot.
Result:no difference
uninstalled Node.js 8.16.0, installed Node.js 10.15.3
Result: all errors gone.

(Might be usefull to add a small note to the Howto)
