### ISSUE TITLE
React-Hot-Loader: AppContainer should be patched

### ISSUE THREAD

**Issue by iamrob-nl** [mendix/pluggable-widgets-generator#25]
This error occurred after creating a new Mendix 8 project (no collaboration), then creating a new widget with the Pluggable Widgets Generator and running 'npm run start'.

When using the widget on the homepage, this restraints the page from displaying in the browser (progressbar only).

![image](https://user-images.githubusercontent.com/8000315/63247338-1b7a5c00-c265-11e9-9caa-2a8cf6353ec9.png)

**Comment by diego-antonelli** [comment]
Hi, which version of the generator are you using?

**Comment by iamrob-nl** [comment]
I have just updated and checked this in version 8.0.0.
https://www.npmjs.com/package/@mendix/generator-widget

**Comment by diego-antonelli** [comment]
Which version is your npm and node?
Make sure you didn't delete the `export default hot(WidgetName);` from your Widget main class.

**Comment by iamrob-nl** [comment]
NPM v6.10.2
Node v10.15.3

I haven't deleted/altered the export default rule, though I was thinking something needed to change there.

**Comment by diego-antonelli** [comment]
@iamrob-nl @hot-loader/react-dom was launched with version 16.9.0 5 days ago and we are not using this version at Mendix yet, so I'll publish a new version of the generator soon.

**Comment by diego-antonelli** [comment]
@iamrob-nl fixed in version 8.0.1 just published

**Comment by austinaylworth** [comment]
I recently updated npm and it looks like this issue cropped back up again.

**Comment by austinaylworth** [comment]
![image](https://user-images.githubusercontent.com/61324996/84038556-b6176900-a965-11ea-9385-e273d21a3ed4.png)

**Comment by diego-antonelli** [comment]
Hi, just make sure its updated, we removed all the hot reload involving react-hot-loader patch!

**Comment by diego-antonelli** [comment]
Are you using custom webpack config?

**Comment by austinaylworth** [comment]
Yes sir. Lemme get things reinstalled and start over. Maybe I missed updating something along the way.

**Comment by diego-antonelli** [comment]
Delete your node_modules, this cannot happen anymore because we are not using it :)

**Comment by diego-antonelli** [comment]
If you are using custom webpack, then you need to remove things related to react-hot-loader or compare your file with the new webpack config we introduced for dev
