### ISSUE TITLE
Error while generating native widget

### ISSUE THREAD

**Issue by bartrikers** [mendix/pluggable-widgets-generator#35]
Hi,

I'm trying to build a pluggable native widget using [this how to](https://docs.mendix.com/howto/extensibility/build-native-widget) but I can't seem to generate a new widget using the Widget Generator(v8.2.0). 

I get the following error:
![widgetgenerator](https://user-images.githubusercontent.com/23105910/69436697-26e89200-0d42-11ea-8fae-e222c05c155c.png)

When I try to open it in Visual Studio Code, I see the following error in the GroupBox.tsx file:
![image](https://user-images.githubusercontent.com/23105910/69436779-57c8c700-0d42-11ea-85ea-9482a7b168a1.png)
![image](https://user-images.githubusercontent.com/23105910/69436795-5eefd500-0d42-11ea-8dc3-9e94a12a69a3.png)

I also tried generating a pluggable widget for web/hybrid, this goes without problem, so to me, it looks like there is something wrong with the native widget generator...

Kind regards,
Bart

**Comment by proggreg** [comment]
The plain javascript template works

**Comment by diego-antonelli** [comment]
Hi Bart, to solve this problem just update the generator using `npm install -g @mendix/generator-widget` because we are already in version 8.4.0

**Comment by bartrikers** [comment]
@diego-antonelli great, thanks!

Perhaps a good idea to update this how-to (https://docs.mendix.com/howto/extensibility/build-native-widget) though, because there it specifically mentions v8.2.0...

Kind regards,
Bart

**Comment by diego-antonelli** [comment]
Thanks for the tip, I’ll let @IIsaku know about this and make the relevant changes.
