### ISSUE TITLE
Deprecated warnings and EPERM operation not permitted error

### ISSUE THREAD

**Issue by therden-siemens** [mendix/pluggable-widgets-generator#36]
Hi. When trying to follow the "Build a Pluggable Web Widget" tutorial I receive mutlilpe warnings and errors.

What appears critical to me is a corrupted tarball archive for react and then a couple of errors with number -4048. 

Please see attached screenshot for details:

![2019-11-22 16_23_55-Administrator_ Node js command prompt](https://user-images.githubusercontent.com/50627577/69438358-2ac9e380-0d45-11ea-992a-6b0f970f7446.png)

node.js version: v12.13.1
npm version: 6.12.1
MX Widget Generator version: 8.4.0

**Comment by diego-antonelli** [comment]
Hi, can you please test again and see if the problem persists?

**Comment by therden-siemens** [comment]
Hi Diego. Yes. I just tested and the issue is still present. Posting a screenshot again (showing only parts of the errors this time)
![2019-11-26 10_12_46-Administrator_ Eingabeaufforderung](https://user-images.githubusercontent.com/50627577/69615676-96f26300-1035-11ea-8182-3f1db4d21ff4.png)

**Comment by diego-antonelli** [comment]
Seems like some error in React Native library itself. Can you please:
1st, re-update the generator, because we retracted the version to 8.3.0
2st, try to re-generate the widget. If you want to test with an existing widget project, please make sure you delete node_modules folder and package-lock.
