### ISSUE TITLE
The arrow keys options don't work in Git Bash

### ISSUE THREAD

**Issue by Rvthof** [mendix/pluggable-widgets-generator#40]
Hi,
When I try to use the generator, I can't change the options that need the arrow keys in Git Bash.
The bash simply moves my prompt up and down.
Work around is to use powershell, but I prefer using git bash, so would love to see this small issue fixed!

**Comment by IIsaku** [comment]
Hi @Rvthof,

Unfortunately, Git Bash doesn't support interactive native applications: https://github.com/git-for-windows/git/wiki/FAQ#some-native-console-programs-dont-work-when-run-from-git-bash-how-to-fix-it.

You could always give the Bash shell from WSL on Windows 10 a try.

Greetings,

Isa Isaku
