### ISSUE TITLE
I often get out-of-memory errors

### ISSUE THREAD

**Issue by ChrisdeG** [mendix/pluggable-widgets-generator#48]
It will work for a while again with "npm run dev". Happens every 30 minutes or so.

The stack trace is like this:

[19640:0000024E7566BEE0]  3498698 ms: Mark-sweep 1392.4 (1425.6) -> 1392.1 (1426.1) MB, 542.8 / 0.0 ms  (average mu = 0.086, current mu = 0.006) allocation failure scavenge might not succeed
[19640:0000024E7566BEE0]  3499204 ms: Mark-sweep 1393.2 (1426.1) -> 1392.9 (1427.1) MB, 502.6 / 0.0 ms  (average mu = 0.049, current mu = 0.007) allocation failure scavenge might not succeed

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0000007EF37DC5C1]
Security context: 0x03496b31e6e9 <JSObject>
    1: /* anonymous */ [00000252DA1FADB9] [C:\Users\Chris de Gelder\Documents\Mendix\ResourceScheduler-main\CustomWidgets\ResourceSchedulerReact\node_modules\webpack\node_modules\acorn\dist\acorn.js:~2167] [pc=0000007EF70F7E39](this=0x01e24d4e7e21 <Parser map = 000003413952CCB1>,refDestructuringErrors=0x00a560a72d99 <DestructuringErrors map = 000003413954E...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF6D95E832A v8::internal::GCIdleTimeHandler::GCIdleTimeHandler+4506
 2: 00007FF6D95C2DB6 node::MakeCallback+4534
 3: 00007FF6D95C3730 node_module_register+2032
 4: 00007FF6D98DC14E v8::internal::FatalProcessOutOfMemory+846
 5: 00007FF6D98DC07F v8::internal::FatalProcessOutOfMemory+639
 6: 00007FF6D9AC2874 v8::internal::Heap::MaxHeapGrowingFactor+9620
 7: 00007FF6D9AB9856 v8::internal::ScavengeJob::operator=+24550
 8: 00007FF6D9AB7EAC v8::internal::ScavengeJob::operator=+17980
 9: 00007FF6D9AC0BF7 v8::internal::Heap::MaxHeapGrowingFactor+2327
10: 00007FF6D9AC0C76 v8::internal::Heap::MaxHeapGrowingFactor+2454
11: 00007FF6D9BEAF17 v8::internal::Factory::NewFillerObject+55
12: 00007FF6D9C68106 v8::internal::operator<<+73494
13: 0000007EF37DC5C1

**Comment by diego-antonelli** [comment]
This is related to you node memory, not the generator itself

**Comment by ChrisdeG** [comment]
Why is it working for some time?

**Comment by diego-antonelli** [comment]
Because it keeps watching files through a node process. You can check how to increase the memory here -> https://futurestud.io/tutorials/node-js-increase-the-memory-limit-for-your-process

Im closing this ticket as this is not an issue for the generator perspective
