### ISSUE TITLE
ProperyGroups 2 level not working

### ISSUE THREAD

**Issue by Boris-Scharinger** [mendix/pluggable-widgets-generator#50]
<widgetname>.xml contains properties and propertygroups.
<propertyGroup caption="this is tab level"> works on first level, leading to tabs in the widget configuration view.
<propertyGroup caption="this is tab level">
     <propertyGroup caption="this is optical group with in a tab">
does not work and leads to "missing properties" all over the place when 'dev'-script is running.

**Comment by diego-antonelli** [comment]
Hi @Boris-Scharinger. This is a problem related to this repo https://github.com/mendix/pluggable-widgets-typing-generator not the generator itself. Please re-open your issue there.
