### ISSUE TITLE
Currently in the last step of the Yeoman generator it freezes

### ISSUE THREAD

**Issue by Marnix-IxD** [mendix/pluggable-widgets-generator#7]
Add unit tests for the widget ? (recommended for Full Boilerplate) (Y/n)

At this last question the Yeoman generator seems to get stuck in Visual Studio. And I can't type yes or no or Y or N, also the enter key doesn't work.

I selected Full Boilerplate

**Comment by diego-antonelli** [comment]
@Marnix-IxD can you please provide screenshots, logs, or something that can help us to identify the problem?

**Comment by Marnix-IxD** [comment]
![yoMendixWidgetGeneratorBug](https://user-images.githubusercontent.com/1084956/59962996-42c6de00-94ed-11e9-87ed-ddc8f2f22c3a.PNG)

This is a screenshot of where it is stuck generating the new widget. Whether I choose full boiler plate or empty widget doesn't change the outcome. I don't know how else I can debug the Yo @mendix/widget generator. So if you can provide other methods. I would love to hear about them.

**Comment by diego-antonelli** [comment]
Which version of node do you have installed and which terminal are you using?

**Comment by Marnix-IxD** [comment]
I'm running node 12.3.1 and i'm using the standard terminal in visual studio

**Comment by diego-antonelli** [comment]
@Marnix-IxD we don't support node 12 yet. Please use 10.15 or 10.16 instead.

**Comment by diego-antonelli** [comment]
@Marnix-IxD If I push a branch with the fix, are you able to test it? Its just necessary to clone the project and do ```npm link``` inside the folder. I've already tested, but would be nice if you can also test before the release.

**Comment by Marnix-IxD** [comment]
Sure I'll take a look at it.

**Comment by Marnix-IxD** [comment]
@diego-antonelli which folder should i clone it to?

**Comment by diego-antonelli** [comment]
You should clone in any desired folder the branch `fix/node_12` and then execute `npm link` inside

**Comment by Marnix-IxD** [comment]
@diego-antonelli pretty sure i'm doing something wrong, i cloned the github branch fix/node_12 and then used npm link inside that folder, that went well. But after that? How do I test that the yeoman generator works? or is it just enough that i can complete these steps?

**Comment by diego-antonelli** [comment]
As soon as you linked you can use the generator normally from the command line `yo @mendix/widget` after test you can unlink using `npm unlink` inside the project cloned.

**Comment by diego-antonelli** [comment]
@Marnix-IxD any results?

**Comment by diego-antonelli** [comment]
@Marnix-IxD we are releasing the new verison, please test it from the normal yo command without npm link

**Comment by Marnix-IxD** [comment]
@diego-antonelli  sorry I did try it, but I couldn't get it to work at first. And didn't take the time to retry it. I'll try the new release and hopefully it will work.
