### ISSUE TITLE
Native pluggable widget generated using the widget generator gives runtime error about missing module

### ISSUE THREAD

**Issue by mgroeneweg** [mendix/pluggable-widgets-generator#9]
I want to create a native pluggable widget. To learn how this is done, I started with the how to for pluggable widgets. The online/hybrid part works great. Then I advanced to native pluggable widgets, where I got stuck. I expected the boilerplate widget to just work out of the box so I can learn from it. Just like online/hybrid pluggable widgets. However, I get runtime errors on my iPhone in the Make It Native app about missing modules. Errors are included in text file ErrorOnDevice. I also included the native packager log, which is also quite unhappy.

This is with Mx8 beta 3, I have an iPhone 6S

Reproduction steps based on pluggable widget how to part 1:
https://docs.mendix.com/howto/extensibility/create-a-pluggable-widget-one

Follow the how-to steps with these modifications:
- Base the new project on the Native mobile quickstart template
- Do NOT delete custom widgets
- Create the dataview on the native home page and use a datasource nanoflow

Generate the widget:
MBP-van-Marcel:CustomWidgets marcelgroeneweg$ yo @mendix/widget NativePluggableBoilerplate

  __  ____   __            _     _            _
 |  \/  \ \ / /           (_)   | |          | |
 | \  / |\ V /   __      ___  __| | ____  ___| |_
 | |\/| | > <    \ \ /\ / / |/ _  |/ _  |/ _ \ __|
 | |  | |/ . \    \ V  V /| | (_| | (_| |  __/ |_
 |_|  |_/_/ \_\    \_/\_/ |_|\__._|\__. |\___|\__|
                                   __/ |
                                  |___/
 Generator, version: 0.1.3
 Issues? Please report them at : https://github.com/mendix/pluggable-widgets-generator/issues

? What is the name of your widget? NativePluggableBoilerplate
? Enter a description for your widget Native pluggable boilerplate
? Organization name ITvisors
? Add a copyright ITvisors 2019
? Add a license Apache-2.0
? Initial version 1.0.0
? Author Marcel
? Mendix Project path ../../
? Which programming language do you want to use for the widget? TypeScript
? Which type of widget are you developing? For native mobile apps
? Which template do you want to use for the widget? Full Boilerplate (recommended for beginners)
? Add unit tests for the widget ? (recommended for Full Boilerplate) (Y/n) N

This completes successfully with the message to open Studio Pro and start playing with the new widget.

Then I run the project and use the Make It Native app. I typed the URL as scanning it causes a flood of native compilations.
The Make It Native app complains that the URL is no Mendix app or produces the error message as in ErrorOnDevice.txt. By then the native packager log also has errors.
[native_packager_log.txt](https://github.com/mendix/pluggable-widgets-generator/files/3388661/native_packager_log.txt)
[ErrorOnDevice.txt](https://github.com/mendix/pluggable-widgets-generator/files/3388663/ErrorOnDevice.txt)

Also reported as support ticket 85805

**Comment by diego-antonelli** [comment]
@mgroeneweg Can you please provide your Node version?

**Comment by mgroeneweg** [comment]
Hi Diego,

I'm on v10.9.0. I already updated the ticket with more info, there is a case issue with the folder names. Changing the module names in the xml files to lower case solved the error, issue is that the widget generator should generate lower case module names to prevent the error.

With regards,

Marcel

**Comment by diego-antonelli** [comment]
Fixed on version 0.1.4 of the generator, please use `yo @mendix/widget` and check if you are in the correct version.

**Comment by mgroeneweg** [comment]
Solved
